modLoader="javafml"
loaderVersion="[1,)"
license="GNU General Public License v3 (GPLv3)"

[[mods]]
modId="shh"
version="1.21.1-1.0.0"
displayName="Scalar Horizon Helper"
logoFile="shh.png"
authors="Lemon_Juiced"
description='''Helper Mod for the Scalar Horizons Modpack'''

[[dependencies.shh]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.200,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.shh]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="NONE"
    side="BOTH"
[[dependencies.shh]]
    modId="roots"
    type="required"
    versionRange="[4.0.0.19-alpha,)"
    ordering="AFTER"
    side="BOTH"